// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelegramAspMvcDotnetBotDb;

namespace telegram_asp_mvc_dotnet_bot_db.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20210423133728_games")]
    partial class games
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TelegramAspMvcDotnetBotDb.Models.Flag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageName");

                    b.HasIndex("Number");

                    b.ToTable("Flags");
                });

            modelBuilder.Entity("TelegramAspMvcDotnetBotDb.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FlagID")
                        .HasColumnType("int");

                    b.Property<bool?>("IsAnswewred")
                        .HasColumnType("bit");

                    b.Property<int>("IsWin")
                        .HasColumnType("int");

                    b.Property<int>("PlayerID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlagID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("TelegramAspMvcDotnetBotDb.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LastName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("TGId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TGId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TelegramAspMvcDotnetBotDb.Models.Game", b =>
                {
                    b.HasOne("TelegramAspMvcDotnetBotDb.Models.Flag", "Flag")
                        .WithMany("Games")
                        .HasForeignKey("FlagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelegramAspMvcDotnetBotDb.Models.Player", "Player")
                        .WithMany("Games")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flag");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TelegramAspMvcDotnetBotDb.Models.Flag", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("TelegramAspMvcDotnetBotDb.Models.Player", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
